### ISSUE TITLE
Current algorithm adds redirect pages to search urls db

### ISSUE THREAD

**Issue by erpheus** [gjulianm/tabtosearch#1]
Just click on a google result, then type google on the ulr bar, press tab, write anything, press enter, and you will be redirected to the earlier result.

**Comment by gjulianm** [comment]
I can't reproduce it. Exact steps don't redirect me. What URL are you
getting in Google Search?

## 

Guillermo Julián
Twitter http://twitter.com |  Blog http://nuncaalaprimera.com

**Comment by erpheus** [comment]
I can't get the plugin to use that saved pattern anymore, but here is a sample log when searching "asdaad" and clicking the first result:

```
info: tabtosearch: google.es matched with http://www.google.es/url?sa=t&rct=j&q={0}&esrc=s&source=web&cd=1&ved=0CDoQFjAA&url=http%3A%2F%2Fwww.guardian.co.uk%2Fmedia%2Fvideo%2F2009%2Fmar%2F18%2Fadvertising-asda&ei=VexRUf6qO5G5hAfN14CQAw&usg=AFQjCNG4ZLieBTPYOW-KmKUQCXoaD5vn3w&bvm=bv.44342787,d.ZG4
```

This url just redirects to the guardian. It is not a search page.
